import SideBar from '<tailwandcss>/components/SideBar';
import '../styles/globals.css';
export const metadata = {
	title: 'ChatGpt Clone',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<div className='flex'>
					{/* Slidebar */}
					<div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>
						<SideBar />
					</div>
					{/* ClientProvider-Notification */}
					<div className='bg-[#343541] flex-1'>{children}</div>
				</div>
			</body>
		</html>
	);
}
